#!/usr/bin/env python3
"""Generate Gitea CODEOWNERS rules from the canonical GitHub rules."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path
from typing import Iterable


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = REPOSITORY_ROOT / ".github" / "CODEOWNERS"
DEFAULT_MAPPING = REPOSITORY_ROOT / ".gitea" / "codeowners.map"
DEFAULT_OUTPUT = REPOSITORY_ROOT / ".gitea" / "CODEOWNERS"

GENERATED_HEADER = """\
# Generated by mgr/sync_codeowners.py from .github/CODEOWNERS.
# Do not edit this file directly. Update the source and run the generator.
# Gitea uses Go regular expressions and combines all matching rules.
# GitHub-to-Gitea handle changes belong in .gitea/codeowners.map.

"""


def parse_codeowners(contents: str) -> list[tuple[str, list[str]]]:
    """Read the GitHub CODEOWNERS subset used by this repository."""
    rules: list[tuple[str, list[str]]] = []

    for line_number, raw_line in enumerate(contents.splitlines(), start=1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue

        tokens = line.split()
        if len(tokens) < 2:
            raise ValueError(f"CODEOWNERS line {line_number} has no owners")

        pattern, owners = tokens[0], tokens[1:]
        for owner in owners:
            if not owner.startswith("@"):
                raise ValueError(
                    f"CODEOWNERS line {line_number}: owner {owner!r} must start with @"
                )

        rules.append((pattern, owners))

    return rules


def _escape_for_gitea_tokenizer(regex: str) -> str:
    # Gitea consumes one level of backslash escaping while tokenizing a line.
    return regex.replace("\\", "\\\\")


def convert_pattern(pattern: str) -> str:
    """Convert the simple GitHub glob patterns in this repository to Gitea regex."""
    if not pattern or pattern.startswith("!"):
        raise ValueError(f"unsupported GitHub CODEOWNERS pattern: {pattern!r}")
    if any(character in pattern for character in ("?", "[", "]")):
        raise ValueError(f"unsupported GitHub CODEOWNERS pattern: {pattern!r}")
    if "**" in pattern or pattern.count("*") > 1:
        raise ValueError(f"unsupported GitHub CODEOWNERS pattern: {pattern!r}")
    if "*" in pattern and not pattern.endswith("*"):
        raise ValueError(f"unsupported GitHub CODEOWNERS pattern: {pattern!r}")
    if any(character.isspace() for character in pattern) or "#" in pattern:
        raise ValueError(f"unsupported GitHub CODEOWNERS pattern: {pattern!r}")

    if pattern == "*":
        return ".*"

    root_relative = pattern.removeprefix("/").removesuffix("/")
    if not root_relative:
        raise ValueError(f"unsupported GitHub CODEOWNERS pattern: {pattern!r}")

    if root_relative.endswith("*"):
        regex = re.escape(root_relative[:-1]) + ".*"
    else:
        regex = re.escape(root_relative) + "(/.*)?"

    return _escape_for_gitea_tokenizer(regex)


def _normalize_handle(handle: str, line_number: int) -> str:
    normalized = handle.removeprefix("@").strip()
    if (
        not normalized
        or any(character.isspace() for character in normalized)
        or normalized.count("/") > 1
        or any(not component for component in normalized.split("/"))
    ):
        raise ValueError(f"mapping line {line_number}: invalid handle {handle!r}")
    return normalized


def parse_owner_mapping(contents: str) -> dict[str, str]:
    """Parse `old-handle = new-handle` entries, without leading @ signs."""
    mapping: dict[str, str] = {}

    for line_number, raw_line in enumerate(contents.splitlines(), start=1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        if line.count("=") != 1:
            raise ValueError(
                f"mapping line {line_number}: expected 'github-handle = gitea-handle'"
            )

        source_text, target_text = line.split("=", 1)
        source = _normalize_handle(source_text, line_number)
        target = _normalize_handle(target_text, line_number)
        if source in mapping:
            raise ValueError(f"mapping line {line_number}: duplicate source handle {source!r}")
        mapping[source] = target

    return mapping


def render_gitea_codeowners(
    rules: Iterable[tuple[str, list[str]]], mapping: dict[str, str]
) -> str:
    output = [GENERATED_HEADER]

    for pattern, owners in rules:
        converted_owners = [
            "@" + mapping.get(owner.removeprefix("@"), owner.removeprefix("@"))
            for owner in owners
        ]
        output.append(f"{convert_pattern(pattern)} {' '.join(converted_owners)}\n")

    return "".join(output)


def _read_mapping(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return parse_owner_mapping(path.read_text(encoding="utf-8"))


def _diff(actual: str, expected: str, output_path: Path) -> str:
    return "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(output_path),
            tofile=f"{output_path} (generated)",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that .gitea/CODEOWNERS is current without changing it",
    )
    args = parser.parse_args()

    try:
        rules = parse_codeowners(DEFAULT_SOURCE.read_text(encoding="utf-8"))
        mapping = _read_mapping(DEFAULT_MAPPING)
        expected = render_gitea_codeowners(rules, mapping)
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            actual = DEFAULT_OUTPUT.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"error: {DEFAULT_OUTPUT} does not exist", file=sys.stderr)
            return 1
        if actual != expected:
            print(_diff(actual, expected, DEFAULT_OUTPUT), file=sys.stderr, end="")
            print(
                "error: generated CODEOWNERS is stale; "
                "run python3 mgr/sync_codeowners.py",
                file=sys.stderr,
            )
            return 1
        print(f"{DEFAULT_OUTPUT.relative_to(REPOSITORY_ROOT)} is up to date")
        return 0

    DEFAULT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    DEFAULT_OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {DEFAULT_OUTPUT.relative_to(REPOSITORY_ROOT)} ({len(rules)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
