#!/usr/bin/env perl
use Env;
Import qw ( env INCLUDE LIB BIN BUILD OBJ);
(my $build = $OBJ) =~ s/\#//g;
$build =~ s/\\/\//g;
(my $obj_dir = DirPath '.') =~ s/\\/\//g;
(my $Dir = $obj_dir) =~ s/$build\///g;
my $ObjDir = "#" . $obj_dir; 
my $STAR_SYS = $env->{ENV}->{STAR_SYS};
my $pkg = "stic";
print "build $pkg with cons\n";
my $PKG  = $pkg . $env->{SUFEXE};
my $DIR = Cwd::cwd(); 
my $YACC = "yacc";
my $YACCLIB = "-ly";
my $LEX  = "lex";
#my $LIBPATH = $env->{LIBPATH}; print "`============================================================ LIBPATH = $LIBPATH\n";
my $LIBPATH = $env->{Packages}->{spack}->{LIBDIR}; #print "`============================================================ LIBPATH = $LIBPATH\n";
#my $LD_LIBRARY_PATH = $env->{ENV}->{LD_LIBRARY_PATH};
#    print "LD_LIBRARY_PATH = $LD_LIBRARY_PATH\n";
# my @words = split ':',$LD_LIBRARY_PATH;
# # find spack path
# foreach my $path (@words) {
# #    print "path = $path\n";
#     if ($path =~ /view/) {
# 	$LIBPATH =  $path;
# #	print "LIBPATH = $LIBPATH\n";
# 	last;
#     }
# }
my $LEXLIB = " -ll";
my $CFLAGS = $env->{CFLAGS};# print "CFLAGS = $CFLAGS\n";
$CFLAGS =~  s/\-m32//g;     # print "CFLAGS = $CFLAGS\n";
my $LDFLAGS   = $env->{LDFLAGS};
$LDFLAGS =~ s/\-m32//;
if ($STAR_SYS =~ /i386/ or $STAR_SYS =~ /^sl5/) {
  $YACC = "/usr/bin/bison -y";
  $YACCLIB = "";
  $LEX = "flex";
  $LEXLIB = "-lfl";
} elsif ($STAR_SYS =~ /^al/) {
#  $LEXLIB = "-L" . $CMAKE_PREFIX_PATH . "/lib -lfl";
#   if ($env->{Packages}->{spack}->{LIBDIR}) {
#     $LIBPATH = "";
#     $LEXLIB = $env->{Packages}->{spack}->{LIBDIR} . "/libfl.so.2";
#   } else {
    $LEXLIB = "-lfl";
#   }
}

my $CXX_VERSION= $env->{CXX_VERSION};
# print "DEBUG CXX_VERSION -- $CXX_VERSION\n";

$CPPPATH = "#" . $Dir . "/src" .  $main::PATH_SEPARATOR . $ObjDir . "/src";
my $LD        = $env->{LD}; #!
if ($LD eq 'g++') {
  $LD = "gcc";
}
# if ($LD eq 'gcc' and $STAR_SYS !~ /^sl4/) {$LDFLAGS = "-Wl,-Bstatic";}
if ($LD eq 'gcc' and $CXX_VERSION < 4) {
    $LDFLAGS = "-static -Wl,-Bstatic";
}

$env2 = $env->clone('CPPPATH'      => $CPPPATH, 
		    'LD'           => $LD,
		    'LDFLAGS'      => $LDFLAGS,
		    'CFLAGS'       => $CFLAGS,
		    'EXTRA_LDFLAGS'=> "",
		    'Libraries'    => "",
		    'LIBPATH'      => $LIBPATH,
		    'LIBS'         => $LEXLIB);

Depends $env2 'src/idl-yacc.c', 'src/idl-lex.c';
Depends $env2 'src/idl.y', 'src/stic.h';
Command $env2 'src/y.tab.c', 'src/idl.y',   qq(cd %<:d; $YACC -v %<:f); 
Command $env2 'src/idl-yacc.c', 'src/y.tab.c', 
  qq(sed -e 's/#ifndef YYSTYPE/#ifndef BUG_IN_AIX/' -e 's/#define YYSTYPE/#define BUG_IN_AIX/' %< > %>);
Command $env2 'src/lex.yy.c', 'src/idl.l', qq(cd %<:d; $LEX %<:f;);
Command $env2 'src/idl-lex.c', 'src/lex.yy.c', 
  qq(sed -e 's/FILE \*yyin = {stdin},/FILE/' -e '/static void __yy__unused() { main(); }/d' %< > %>);
script::Keep $pkg;
my @src = qw(src/idl-yacc.c src/templateStuff.c);
Program      $env2 $pkg, @src;
Install $env2 $BIN, $pkg;
  
